#include "led.h"

#define GPIO_MODER_OUTPUT 1
#define GPIO_MODER_ALTARNATE 2
#define GPIO_MODER_ANALOG 3
#define TIM_CCMR1_PWM_MODE_1 6
#define TIM_CCMR1_CC1S_OUTPUT 0

void led_init(void){
	//User led
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOCEN;	
	GPIOC->MODER = (GPIO_MODER_OUTPUT << GPIO_MODER_MODE13_Pos) | (GPIO_MODER_OUTPUT << GPIO_MODER_MODE14_Pos);
	GPIOC->ODR |= GPIO_ODR_OD13;
	GPIOC->ODR &= ~GPIO_ODR_OD14;
	//RGB led
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN;
	GPIOA->MODER |= (GPIO_MODER_ALTARNATE << GPIO_MODER_MODE8_Pos) | (GPIO_MODER_ALTARNATE << GPIO_MODER_MODE9_Pos) | (GPIO_MODER_ALTARNATE << GPIO_MODER_MODE10_Pos);
	GPIOA->AFR[1] |= GPIO_AFRH_AFRH0_0 | GPIO_AFRH_AFRH1_0 | GPIO_AFRH_AFRH2_0;
	//pwm
	RCC->APB2ENR |= RCC_APB2ENR_TIM1EN;
	TIM1->PSC = 0;
	TIM1->ARR = 10000; // 10 kHz
	TIM1->CCR1 = 0;
	TIM1->CCR2 = 0;
	TIM1->CCR3 = 0;
	TIM1->CCMR1 |= (0 << TIM_CCMR1_CC1S_Pos) | (TIM_CCMR1_PWM_MODE_1 << TIM_CCMR1_OC1M_Pos);
	TIM1->CCMR1 |= (0 << TIM_CCMR1_CC2S_Pos) | (TIM_CCMR1_PWM_MODE_1 << TIM_CCMR1_OC2M_Pos);
	TIM1->CCMR2 |= (0 << TIM_CCMR2_CC3S_Pos) | (TIM_CCMR1_PWM_MODE_1 << TIM_CCMR2_OC3M_Pos);
	TIM1->CCER |= TIM_CCER_CC1E | TIM_CCER_CC2E | TIM_CCER_CC3E;
	TIM1->BDTR |= TIM_BDTR_MOE;
	TIM1->CR1 |= TIM_CR1_CEN;
}

void ledShowRgb(uint8_t red, uint8_t green, uint8_t blue){
	TIM1->CCR1 = (red/255)*10000; // red
	TIM1->CCR2 = (green/255)*10000; // green
	TIM1->CCR3 = (blue/255)*10000; // blue
}
